CREATE TABLE IF NOT EXISTS "sala" (
	"id" INTEGER NOT NULL,
	"bloco" VARCHAR NOT NULL,
	"desc " INTEGER NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "switch" (
	"id" INTEGER NOT NULL,
	"nome" VARCHAR,
	"num_portas" INTEGER NOT NULL,
	"mac_addr" VARCHAR NOT NULL UNIQUE,
	"ip_addr" VARCHAR NOT NULL,
	"sala" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("sala") REFERENCES "sala"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "porta" (
	"Id" INTEGER NOT NULL UNIQUE,
	"porta" INTEGER NOT NULL,
	"switch" INTEGER NOT NULL,
	"status" BOOLEAN NOT NULL DEFAULT 1,
	"reservada" BOOLEAN NOT NULL,
	PRIMARY KEY("Id"),
	FOREIGN KEY ("switch") REFERENCES "switch"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "maquina" (
	"id" INTEGER NOT NULL,
	"porta" INTEGER NOT NULL,
	"ip" VARCHAR NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("porta") REFERENCES "porta"("Id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "usuario" (
	"id" INTEGER NOT NULL,
	"mac_addr" VARCHAR NOT NULL UNIQUE,
	"login" VARCHAR NOT NULL UNIQUE,
	"senha" VARCHAR NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE IF NOT EXISTS "agendamento_porta" (
	"id" INTEGER NOT NULL,
	"id_porta" INTEGER NOT NULL,
	"id_agendamento" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("id_porta") REFERENCES "porta"("Id")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("id_agendamento") REFERENCES "agendamento"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS "agendamento" (
	"id" INTEGER NOT NULL,
	"inicio" DATETIME NOT NULL,
	"fim" DATETIME NOT NULL,
	"criado_por" INTEGER NOT NULL,
	PRIMARY KEY("id"),
	FOREIGN KEY ("criado_por") REFERENCES "usuario"("id")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);


